name: Build and Deploy Lambda

on:
  push:
    branches:
      - main

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    env:
      S3_BUCKET_NAME: your-lambda-s3-bucket-name
      S3_KEY: lambda/csv-processor.zip

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build shaded JAR
        run: mvn clean package

      - name: Create Lambda ZIP
        run: |
          mkdir build
          cp target/lambda-csv-processor-1.0-SNAPSHOT-shaded.jar build/
          cd build
          zip csv-processor.zip lambda-csv-processor-1.0-SNAPSHOT-shaded.jar

      - name: Upload ZIP to S3
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::657454854557:role/GitHubActionsLambaRepoRole
          aws-region: eu-west-2

      - name: Push ZIP to S3
        run: |
          aws s3 cp build/csv-processor.zip s3://$S3_BUCKET_NAME/$S3_KEY
